DATASET:
  BOS_IDX: 2
  EOS_IDX: 3
  MIN_FREQ: 10
  NAME: IWSLT2017
  PAD_IDX: 1
  SPECIAL_SYMBOLS:
  - unk
  - pad
  - bos
  - eos
  SRC_LANGUAGE: de
  TGT_LANGUAGE: en
  UNK_IDX: 0
LR_SCHEDULER:
  FACTOR: 0.1
  MODE: min
  NAME: ReduceLROnPlateau
  PATIENCE: 3
  THRESHOLD: 1.0e-05
MODEL:
  DEC_DROPOUT: 0.5
  DEC_EMBED_DIM: 256
  DEC_HIDDEN_DIM: 512
  ENC_BIDIRECTIONAL: true
  ENC_DROPOUT: 0.5
  ENC_EMBED_DIM: 256
  ENC_HIDDEN_DIM: 512
OPTIMIZER:
  CLIP: 1
  EPS: 1.0e-06
  LR: 1.0
  NAME: ADADELTA
  RHO: 0.9
  WEIGHT_DECAY: 0.9
SYSTEM:
  NUM_GPUS: 1
TEST:
  BATCH_SIZE: 1
TRAIN:
  BATCH_SIZE: 64
  N_EPOCHS: 50
VAL:
  BATCH_SIZE: 32
